name: first_proyect
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.9.0
  firebase_storage: ^10.2.18
  firebase_messaging: ^12.0.1
  localstorage: ^4.0.0
  google_api_availability: ^3.0.1
  uuid: 3.0.6
  open_file: ^3.2.1
  image_picker: ^0.8.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.3.0
  localstore: ^1.2.3
  io: ^1.0.3
  table_calendar: ^3.0.6
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  nice_intro: ^0.2.1
  simple_speed_dial: ^0.1.7
  charts_flutter: ^0.12.0
  firebase_database: ^9.1.3
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_app_name: ^0.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: Assets/AnarchySimpleLogo.png
  min_sdk_android: 21
    
flutter_app_name:
  name: "AnarchyStores"
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - Assets/
    - fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700        
  #
  fonts:
    - family: Aboreto
      fonts: 
        - asset: fonts/Aboreto-Regular.ttf
    - family: LibreBaskerville
      fonts: 
        - asset: fonts/LibreBaskerville-Regular.ttf
        - asset: fonts/LibreBaskerville-Italic.ttf
        - asset: fonts/LibreBaskerville-Bold.ttf
    - family: NunitoSans
      fonts: 
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-Italic.ttf
        - asset: fonts/NunitoSans-Bold.ttf
        - asset: fonts/NunitoSans-BoldItalic.ttf
        - asset: fonts/NunitoSans-Black.ttf
        - asset: fonts/NunitoSans-BlackItalic.ttf
        - asset: fonts/NunitoSans-ExtraBold.ttf
        - asset: fonts/NunitoSans-ExtraBoldItalic.ttf
        - asset: fonts/NunitoSans-ExtraLight.ttf
        - asset: fonts/NunitoSans-ExtraLightItalic.ttf
        - asset: fonts/NunitoSans-Light.ttf
        - asset: fonts/NunitoSans-LightItalic.ttf
        - asset: fonts/NunitoSans-SemiBold.ttf
        - asset: fonts/NunitoSans-SemiBoldItalic.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/static/PlayfairDisplay-Regular.ttf
        - asset: fonts/static/PlayfairDisplay-Italic.ttf
        - asset: fonts/static/PlayfairDisplay-Bold.ttf
        - asset: fonts/static/PlayfairDisplay-BoldItalic.ttf
        - asset: fonts/static/PlayfairDisplay-Black.ttf
        - asset: fonts/static/PlayfairDisplay-BlackItalic.ttf
        - asset: fonts/static/PlayfairDisplay-ExtraBold.ttf
        - asset: fonts/static/PlayfairDisplay-ExtraBoldItalic.ttf
        - asset: fonts/static/PlayfairDisplay-Italic.ttf
        - asset: fonts/static/PlayfairDisplay-Medium.ttf
        - asset: fonts/static/PlayfairDisplay-MediumItalic.ttf
        - asset: fonts/static/PlayfairDisplay-SemiBold.ttf
        - asset: fonts/static/PlayfairDisplay-SemiBoldItalic.ttf
    - family: ENGR
      fonts:
        - asset: fonts/ENGR.TTF  
uses-material-design: true
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
